project_name: 'my-process-1'
dataset_path: './demos/my_data/profile_complete.parquet'  # path to your dataset
export_path: '/mnt_fast/test/data_juicer_output/export'

use_cache: false
executor_type: ray

process:
  - my_video_splitter:
      output_dir: '/mnt_fast/test/data_juicer_output/split_videos'
      batch_size: 1
      num_proc: 10
      cpu_required: 11
  - my_aesthetic_preprocess:
      clip_model_path: '/mnt_fast/pretrained_models/ViT-L-14.pt'
      num_proc: 5
      cpu_required: 6.94
  - my_aesthetic_process:
      weight_model_path: '/mnt_fast/pretrained_models/aesthetic.pth'
      clip_model_path: '/mnt_fast/pretrained_models/ViT-L-14.pt'
      num_proc: 1
      gpu_required: 0.1
  - my_ocr_preprocess:
      num_proc: 5
      cpu_required: 7.48
  - my_ocr_process:
      model_path: '/mnt_fast/pretrained_models/craft_mlt_25k.pth'
      gpu_required: 0.1
  - my_optical_preprocess:
      num_proc: 5
      cpu_required: 6.45
  - my_optical_process:
      model_path: '/mnt_fast/pretrained_models/gmflow-scale2-regrefine6-mixdata-train320x576-4e7b215d.pth'
      num_proc: 1
      gpu_required: 0.1